### ISSUE TITLE
Assing meeting_id to topics and mark selected after meeting is created

### ISSUE THREAD

**Issue by JuddL333** [LasVegasRubyGroup/soapbox#10]
After a creating a meeting, the topics are not associated with the meeting. This is required for kudos to be awarded. Also, the state of the topic needs to move from 'open' to 'selected.

**Comment by brianvh** [comment]
Fixed by 72418b666d2c7a6318188b2464c47f73d19e5e38 and 72418b666d2c7a6318188b2464c47f73d19e5e38
